### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by ningqing123** [SysCV/qdtrack#10]
when I train the net,Epoch 1 ,200/171305 ,the result as follow:
lr: 7.992e-03,loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 81.8194, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
why?

**Comment by OceanPang** [comment]
It seems that you are only using 1 GPU for training and our config uses 8 GPUs.

**Comment by ningqing123** [comment]
I debug it,I find that tracking-train-data has 27809 img,but build dataset the count is 27331.I don't know. expect to your reply。

**Comment by OceanPang** [comment]
This is because we filter the empty images (do not have annotated objects) during training.

**Comment by ningqing123** [comment]
but the visualization result of the annotation I transformed has 27809.

**Comment by ningqing123** [comment]
Can you provide your annotation( transformed )?

**Comment by ningqing123** [comment]
I got it and solve this the problem,I modify the config uses 1 GPU.
