### ISSUE TITLE
Example code for inference?

### ISSUE THREAD

**Issue by sarimmehdi** [SysCV/qdtrack#104]
Can you provide a quick example that shows how to do inference per image. I had a look at your [inference api](https://github.com/SysCV/qdtrack/blob/6f8a4e17f381fe6a5e4f90519305b32115927c73/qdtrack/apis/inference.py) but I cannot understand how to pass my image files to it. Also, why is your inference model only doing detection but not tracking?

**Comment by OceanPang** [comment]
New inference code available at [here](https://github.com/SysCV/qdtrack/blob/master/tools/inference.py).
