### ISSUE TITLE
Could you please provide the processed CocoVID style BDD100k data?

### ISSUE THREAD

**Issue by happinesslz** [SysCV/qdtrack#11]
@fyu @OceanPang  Thanks for your great work!  Could you please provide the processed CocoVID style BDD100k data?

**Comment by OceanPang** [comment]
Is there any problem for you to convert the JSON file with our provided script? You can show your problems here and we can solve them for you.

**Comment by happinesslz** [comment]
@OceanPang   what's the "annotations" on the project? I only download the "labels-20" from the BDD100k official website. Or could you provide the files which need to downloaded from the BDD100k official web in details?

**Comment by happinesslz** [comment]
@OceanPang  
![image](https://user-images.githubusercontent.com/40748327/103443049-356be180-4c96-11eb-9d32-39d2fc62568a.png)

**Comment by happinesslz** [comment]
@OceanPang @fyu  The official web only provides the download files:
1.Videos, 2. Video Torrent, 3. Video Parts, 4. Info, 5. Images, 6. Labels, 7. Drivable Maps, 8. Segmentation, 9. MOT 2020 Labels, 10, MOT 2020 Data, 11. Detection 2020 Labels

I am very confuse, please tell me how to organize the structure as:
│ │ ├── tracking
│ │ │ ├── images
│ │ │ ├── annotations

**Comment by OceanPang** [comment]
Please refer to the updated [DOC](https://github.com/SysCV/qdtrack/blob/master/docs/GET_STARTED.md).
