### ISSUE TITLE
Test on MOT17, ModuleNotFoundError: No module named 'qdtrack'

### ISSUE THREAD

**Issue by iTruffle** [SysCV/qdtrack#113]
Thank you for your great work.
when i tested on MOT17，I got an error like this:
ModuleNotFoundError: No module named 'qdtrack'
![image](https://user-images.githubusercontent.com/80766557/184272188-6a8a2494-02b0-4100-8ae8-105962132af9.png)
And what is the '[--out ${RESULT_FILE}]'? And how should I named it? Should I named the file 'out.pkl'?

**Comment by OceanPang** [comment]
Please first run `python setup.py develop` to install the pkg.

**Comment by carpeug** [comment]
Hi, is it resolved in this way? Because I am still getting this error
