### ISSUE TITLE
Whether QDTrack supports changing detectors or using external detection results for tracking

### ISSUE THREAD

**Issue by unihornWwan** [SysCV/qdtrack#116]
First of all, thank you for your outstanding contribution.
For this paper, Faster R-CNN is used as the detector and RPN output is used to carry out quasi-dense sampling and similarity learning, indicating that RoI feature is needed in the tracking process. Does this mean that external detection results cannot be used for tracking in customized scenes，and we have to train the entire network from detectors to trackers? Thank you !

**Comment by OceanPang** [comment]
You can change detectors by replacing [this line](https://github.com/SysCV/qdtrack/blob/640e3668f3f29be820a878cdc7d14e9a535e53b2/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py#L4). 

You can also directly use public detection results by changing [this line](https://github.com/SysCV/qdtrack/blob/640e3668f3f29be820a878cdc7d14e9a535e53b2/qdtrack/models/mot/qdtrack.py#L161).
