### ISSUE TITLE
no images saved running test.py

### ISSUE THREAD

**Issue by LisaBernhardt** [SysCV/qdtrack#32]
I am running test.py to test your pretrained model on the bdd100k dataset.
I would like to save the painted images with the evaluation e.g. including bounding boxes and track ids into my directory.
After running:
` python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --out testrun.pkl --eval track --show --show-dir ~/01_models/qdtrack/data/results`

my folder ~/01_models/qdtrack/data/results is empty.

arguments from test.py:
```
parser.add_argument('--show', action='store_true', help='show results')
parser.add_argument('--show-dir', help='directory where painted images will be saved')
```
What am I doing wrong? Could you please help me?

**Comment by XiaLiPKU** [comment]
You need to run `mkdir ~/01_models/qdtrack/data/results` before

**Comment by LisaBernhardt** [comment]
Thank you for your message.
I have created the folder `~/01_models/qdtrack/data/results` before I start the validation process with 
`python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --out testrun.pkl --eval track --show --show-dir ~/01_models/qdtrack/data/results`
but it didn't work for me.

However I have solved the problem by writing a small script which plots the results from the .pkl file in the images I am running the validation on.

**Comment by HIT-ShuWei** [comment]
> Thank you for your message. I have created the folder `~/01_models/qdtrack/data/results` before I start the validation process with `python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --out testrun.pkl --eval track --show --show-dir ~/01_models/qdtrack/data/results` but it didn't work for me.
> 
> However I have solved the problem by writing a small script which plots the results from the .pkl file in the images I am running the validation on.

Hey I've met the same problem like you, would you like to share the visualization code kindly?

P.S. I've sent an email to you yesterday~
