### ISSUE TITLE
Result file

### ISSUE THREAD

**Issue by vLaznikova** [SysCV/qdtrack#4]
Hi,

How do I match corresponding images with tracking results?
Is the frame name saved somewhere in pickle file?

Is the format of the output bounding box in a result file [top left, top right]?

Thanks!

**Comment by OceanPang** [comment]
Hi, @vLaznikova, we are using the order of the dataloader to save the tracking results. That is, the order of the outputted results is the same as the one in `Dataset`.  

The final results are [x1, y1, w, h] which is consistent with the coco file, which you may find [x1, y1, x2, y2] during the process.

**Comment by LisaBernhardt** [comment]
@vLaznikova I am having the same issue. Would you mind sharing your code how you matched the corresponding images with the tracking results? Thanks a lot!
