### ISSUE TITLE
In last step of install, get 'pytest' distribution was not found

### ISSUE THREAD

**Issue by diesendruck** [SysCV/qdtrack#5]
Following the install instructions, in the last step, in the qdtrack dir, ran `python setup.py develop` and got the following:
`error: The 'pytest' distribution was not found and is required by motmetrics`

**Comment by diesendruck** [comment]
Ran `python setup.py develop` a second time, and got a different error, on `flake8`. Ran it a third time, and it completed successfully.

**Comment by OceanPang** [comment]
Please try to install these dependencies first, we will also fix these in the `requirements.txt`.

For example, `pip install pytest`.
