### ISSUE TITLE
How to convert the annotations in the detection set

### ISSUE THREAD

**Issue by maoyw57** [SysCV/qdtrack#50]
For 'python -m bdd100k.label.to_coco -m det... ', I can't convert the detection and tracking set.
I don't know and can't find where is 'bdd100k.label.to_coco' or 'det'

**Comment by XiaLiPKU** [comment]
First, you need to run `python setup.py install` to install bdd100k

**Comment by maoyw57** [comment]
> First, you need to run `python setup.py install` to install bdd100k

Thank you!
