### ISSUE TITLE
Problem about convert BDD100K det annotations 

### ISSUE THREAD

**Issue by maoyw57** [SysCV/qdtrack#53]
When I convert det_train.json to det_train_cocofmt.json, I meet this problem in picture.
But I can convert det_val.json and track successfully. I'm confused this situation. 
![1625198117(1)](https://user-images.githubusercontent.com/73291365/124218936-d8aa9000-db2d-11eb-8b93-f89df7e2db84.png)
![1625198117(1)](https://user-images.githubusercontent.com/73291365/124218958-e3fdbb80-db2d-11eb-8266-1d62168de379.png)

**Comment by XiaLiPKU** [comment]
Hi, we have updated our codes.
Please clone the latest version.
Hope this will help you~

**Comment by HIT-ShuWei** [comment]
I've met the same problem like you. Did you solve it ?

By the way I have already updated the latest code but it still doesn't work.
