### ISSUE TITLE
Problem with test on a single GPU 

### ISSUE THREAD

**Issue by xiwang1212** [SysCV/qdtrack#55]
Hey there, 

Thanks for  the nice work and sharing the code! 

I encountered some problems while running the code, and maybe somebody else has already solved it before? 

I am running the test code on a single GPU using the TAO dataset. My command is: 
`python tools/test.py configs/tao/ft_qdtrack_frcnn_r50_fpn_24e_tao.py checkpoint_files/qdtrack_tao.pth --out ./outputs/tao_test.pkl --show-dir ./outputs`

The complete output is: 
> loading annotations into memory...
> Done (t=1.42s)
> creating index...
> index created!
> Use load_from_local loader
> [                                                  ] 0/36375, elapsed: 0s, ETA:/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448238472/work/c10/core/TensorImpl.h:1156.)
>   return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
> /local/home/anaconda3/envs/imut/lib/python3.9/site-packages/mmdet-2.10.0-py3.9.egg/mmdet/models/dense_heads/rpn_head.py:179: UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
>   warnings.warn(
> [                                    ] 1/36375, 2.1 task/s, elapsed: 0s, ETA: 17524sTraceback (most recent call last):
>   File "/pub/scratch/IMUTracking/qdtrack/tools/test.py", line 163, in <module>
>     main()
>   File "/pub/scratch/IMUTracking/qdtrack/tools/test.py", line 135, in main
>     outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
>   File "/pub/scratch/IMUTracking/qdtrack/qdtrack/apis/test.py", line 24, in single_gpu_test
>     result = model(return_loss=False, rescale=True, **data)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
>     return super().forward(*inputs, **kwargs)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
>     return old_func(*args, **kwargs)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/mmdet-2.10.0-py3.9.egg/mmdet/models/detectors/base.py", line 183, in forward
>     return self.forward_test(img, img_metas, **kwargs)
>   File "/local/home/anaconda3/envs/imut/lib/python3.9/site-packages/mmdet-2.10.0-py3.9.egg/mmdet/models/detectors/base.py", line 160, in forward_test
>     return self.simple_test(imgs[0], img_metas[0], **kwargs)
>   File "/pub/scratch/IMUTracking/qdtrack/qdtrack/models/mot/quasi_dense.py", line 94, in simple_test
>     bboxes, labels, ids = self.tracker.match(
>   File "/pub/scratch/IMUTracking/qdtrack/qdtrack/models/trackers/tao_tracker.py", line 158, in match
>     sims = cal_similarity(
> TypeError: cal_similarity() got an unexpected keyword argument 'transpose'

**Comment by siyliepfl** [comment]
Please refer to this #51
