### ISSUE TITLE
Unclear which links to pick from BDD website for dataset prep

### ISSUE THREAD

**Issue by diesendruck** [SysCV/qdtrack#6]
The Readme indicates Detection and Tracking sets, but the site shows 11 options, including:
Images, MOT 2020 Labels, MOT 2020 Data, Detection 2020 Labels.

Also, clicking MOT 2020 Data shows many different options. Should they all be downloaded?

**Comment by fyu** [comment]
Yes, they should be all downloaded for training and evaluation. For the convenience of downloading, the dataset is divided into multiple parts.

**Comment by diesendruck** [comment]
@fyu Thank you for responding.

So we should download all sets from "MOT 2020 Data". What about the other options among the 11 top-level options?

Perhaps some more orientation on the allocation of downloaded content to the suggested folder structure would be very helpful.

Thank you

├── data
│   ├── bdd
│   │   ├── detection
│   │   │   ├── images
│   │   │   ├── annotations
│   │   ├── tracking
│   │   │   ├── images
│   │   │   ├── annotations

**Comment by fyu** [comment]
If you want to do tracking, you only need the data and labels under tracking. However, you may want to pre-train your detector on the detection data set, which means you will need to download `Detection 2020` labels and `Images`.

**Comment by diesendruck** [comment]
For example, for tracking only:
What is the mapping between the 11 options from the BDD site...
1. Videos, 2. Video Torrent, 3. Video Parts, 4. Info, 5. Images, 6. Labels, 7. Drivable Maps, 8. Segmentation, 9. MOT 2020 Labels, 10, MOT 2020 Data, 11. Detection 2020 Labels

... and the directory structure below?

├── data
│ ├── bdd
│ │ ├── tracking
│ │ │ ├── images
│ │ │ ├── annotations

Is it the following?

├── data
│ ├── bdd
│ │ ├── tracking
│ │ │ ├── images <-- Contents of "Images"
│ │ │ ├── annotations <-- Contents of "MOT 2020 Labels"


It will be helpful to know the exact mapping, to proceed with training.

Thank you

**Comment by fyu** [comment]
I am wondering whether you saw the on-site doc for the downloading buttons. Just to make sure, here is the document: https://doc.bdd100k.com/download.html

**Comment by diesendruck** [comment]
Yes, I had seen that. Is the following revised allocation correct for tracking?

├── data
│ ├── bdd
│ │ ├── tracking
│ │ │ ├── images <-- Contents of "MOT 2020 Data"
│ │ │ ├── annotations <-- Contents of "MOT 2020 Labels"

**Comment by OceanPang** [comment]
@diesendruck Please refer to the updated [DOC](https://github.com/SysCV/qdtrack/blob/master/docs/GET_STARTED.md).
