### ISSUE TITLE
Has the default test resolution for TAO changed?

### ISSUE THREAD

**Issue by sukjunhwang** [SysCV/qdtrack#68]
Hi, 

Thanks for sharing and keep updating the repository.
Has the default test resolution for TAO changed from img_scale=(1080, 1080) to img_scale=(1333, 800)?

**Comment by OceanPang** [comment]
Yes, this aims to keep consistent with the descriptions in the paper, and the performance is comparable. 
If you use a (1080, 1080) based multi-scale resize training and test with the same resolution, the performance shall be higher.
