### ISSUE TITLE
Tao error while run "setup.py develop"

### ISSUE THREAD

**Issue by ayanasser** [SysCV/qdtrack#77]
While following the steps of the installation and reach the last line "python setup.py develop"
I got this error: 

```
Processing dependencies for qdtrack==0.1.0+b905d2a
Searching for tao
Reading https://pypi.python.org/simple/tao/
No local packages or working download links found for tao
error: Could not find suitable distribution for Requirement.parse('tao')
```

any clue ?

**Comment by OceanPang** [comment]
Solved in #78 , please try `pip install git+https://github.com/OceanPang/tao.git` to install the TAO API.
