### ISSUE TITLE
Is it possible to drop the unmatched embedding features?

### ISSUE THREAD

**Issue by iAmJuan550** [SysCV/qdtrack#80]
I want to be able to drop the embedding features if they remain unmatched for a few frames. Is it possible to do that with the current codebase?

**Comment by OceanPang** [comment]
Yes, you can tune [this parameter](https://github.com/SysCV/qdtrack/blob/b28af06c7fdb6ce99b967302c0c7e9a557d508bf/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py#L10).

**Comment by iAmJuan550** [comment]
@OceanPang is [this](https://github.com/SysCV/qdtrack/blob/b28af06c7fdb6ce99b967302c0c7e9a557d508bf/configs/tao/qdtrack_frcnn_r101_fpn_24e_lvis.py#L13) also the same parameter?

**Comment by iAmJuan550** [comment]
Thank you, I solved my issue.
