### ISSUE TITLE
TypeError : Resnet : __init__() got an unexpected keyword argument 'init_cfg'

### ISSUE THREAD

**Issue by AmanGoyal99** [SysCV/qdtrack#90]
Greetings,

I am currently using qdtrack in python 3.8, Cuda 11 based environment for RTX 3090 GPU. While training as well as testing, I am getting this error.
All required datasets in required locations have been downloaded and maintained.
Any help would be appreciated.

**Comment by Xiaofei-Kevin-Yang** [comment]
> > We develop this codebase based on mmcv 2.14.0 and mmdet 1.3.10, please update the version of your mmcv.
> 
> I tried installing using `pip install mmcv-full=1.3.10` but I get an error saying that such a version does not exist. @OceanPang

Hi Aman, I got the same issue. I was wondering did you solve it?

**Comment by Xiaofei-Kevin-Yang** [comment]
> We develop this codebase based on mmcv 2.14.0 and mmdet 1.3.10, please update the version of your mmcv.
Hi Ocean, could you please guide me to solve it. Much appreciated!

**Comment by HanGuangXin** [comment]
@AmanGoyal99 , @Xiaofei-Kevin-Yang  This command can be used as the reference:

`pip install mmcv-full==1.3.10 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html`
