### ISSUE TITLE
Possibility of using pre-trained weights for neck and head and only customizing backbone ?

### ISSUE THREAD

**Issue by AmanGoyal99** [SysCV/qdtrack#93]
Greetings,

So I wanted to know the possibility of using pre-trained weights for only neck and head components of qdtrack? I would like to use my own backbone network but use pre-trained weights for neck and head components of qdtrack. Is that possible ? @OceanPang 

Thanks

**Comment by OceanPang** [comment]
You should re-train the model if you modify any weights in the model.
