### ISSUE TITLE
Backbone pre-trained on BDD100K dataset

### ISSUE THREAD

**Issue by AmanGoyal99** [SysCV/qdtrack#95]
Greetings,

How can I access the backbone pre-trained weights on BDD100K dataset ?

Thanks

**Comment by OceanPang** [comment]
You can get the pre-trained models from [here](https://drive.google.com/file/d/1YNAQgd8rMqqEG-fRj3VWlO4G5kdwJbxz/view).

**Comment by AmanGoyal99** [comment]
> You can get the pre-trained models from [here](https://drive.google.com/file/d/1YNAQgd8rMqqEG-fRj3VWlO4G5kdwJbxz/view).

I actually only want pre-trained weights of Resnet-50 on bdd100k actually
