### ISSUE TITLE
'QDTrack' object has no attribute 'tracker'

### ISSUE THREAD

**Issue by gurkirt** [SysCV/qdtrack#97]
Hello, Thank you for this codebase. I am struggling with running it on a in the wild video. My video has 27K frames. Frames are not in coco format. I modified TaoDataset to accept my video but I get the following error. Seems like it has something to do with either installation or tracker module is not present in the code base. 

I changed the load_annos function in the tao dataset to:

    def load_tao_anns(self, ann_file):
            self.coco = CocoVID(ann_file)
            self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
            self.cat2label = {cat_id: i for i, cat_id in enumerate(self.cat_ids)}
    
            data_infos = []
            self.vid_ids = self.coco.get_vid_ids()
            self.img_ids = []
            for vid_id in self.vid_ids:
                print('vid_id', self.vid_ids)
                # img_ids = self.coco.get_img_ids_from_vid(vid_id)
                # print('self.key_img_sampler', img_ids)
                
                # if self.key_img_sampler is not None:
                #     img_ids = self.key_img_sampling(img_ids,
                                                    # **self.key_img_sampler)
                # self.img_ids.extend(img_ids)
                img_ids = [i for i in os.listdir('data/tao/frames/test/1j20qq1JyX4/') if i.endswith('.jpg')]
    
                for img_id, img_name in enumerate(img_ids):
                    
                    info = {'image_id':img_id}
                    # if info['file_name'].startswith('COCO'):
                    #     # Convert form the COCO 2014 file naming convention of
                    #     # COCO_[train/val/test]2014_000000000000.jpg to the 2017
                    #     # naming convention of 000000000000.jpg
                    #     # (LVIS v1 will fix this naming issue)
                    #     info['filename'] = info['file_name'][-16:]
                    # else:
                    info['filename'] = 'test/1j20qq1JyX4/'+img_name
                    data_infos.append(info)
    
            # print('Taon annos ', data_infos)
            return data_infos

I am only trying to run it on one video. 

I use the following command to run it in test mode without eval

    python tools/test.py  configs/tao/qdtrack_frcnn_r101_fpn_12e_tao_ft.py qdtrack_tao_20210812_221438-b6bd07e2.pth --format-only 

Here is the output log when I run test.py. Can you please help?

      loading annotations into memory...
      Done (t=0.03s)
      creating index...
      index created!
      vid_id [2]
      Use load_from_local loader
      [                                                  ] 0/27031, elapsed: 0s, ETA:Traceback (most recent call last):
        File "tools/test.py", line 164, in <module>
          main()
        File "tools/test.py", line 136, in main
          outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
        File "/cluster/home/gusingh/euler-codepad/qdtrack/qdtrack/apis/test.py", line 24, in single_gpu_test
          result = model(return_loss=False, rescale=True, **data)
        File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/modules/module.py", line 727, in _call_impl
          result = self.forward(*input, **kwargs)
        File "/cluster/home/gusingh/envirs/qdtrack/lib64/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
          return super().forward(*inputs, **kwargs)
        File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/parallel/data_parallel.py", line 159, in forward
          return self.module(*inputs[0], **kwargs[0])
        File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/modules/module.py", line 727, in _call_impl
          result = self.forward(*input, **kwargs)
        File "/cluster/home/gusingh/envirs/qdtrack/lib64/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
          return old_func(*args, **kwargs)
        File "/cluster/home/gusingh/envirs/qdtrack/lib64/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
          return self.forward_test(img, img_metas, **kwargs)
        File "/cluster/home/gusingh/envirs/qdtrack/lib64/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
          return self.simple_test(imgs[0], img_metas[0], **kwargs)
        File "/cluster/home/gusingh/euler-codepad/qdtrack/qdtrack/models/mot/qdtrack.py", line 96, in simple_test
          bboxes, labels, ids = self.tracker.match(
        File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/modules/module.py", line 778, in __getattr__
          raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
      torch.nn.modules.module.ModuleAttributeError: 'QDTrack' object has no attribute 'tracker'

**Comment by gurkirt** [comment]
Seems like there is a bug in QDTrack class [here](https://github.com/SysCV/qdtrack/blob/master/qdtrack/models/mot/qdtrack.py#L13) does not initialise the tracker. 
I added self.init_tracker(), it seems to be working.

**Comment by tobiasfshr** [comment]
There is no bug, QDTrack does initialize the tracker, if the frames inside your video start with index 0 (see [here](https://github.com/SysCV/qdtrack/blob/b28af06c7fdb6ce99b967302c0c7e9a557d508bf/qdtrack/models/mot/qdtrack.py#L88)). If they don't, the tracker has no clue when to reset the track graph (i.e. when a new sequence begins), and you will encounter this error. The fix is to make frameIndex start from 0 for all videos in your dataset.
